### ISSUE TITLE
Specific smashable doesn't have a respawn cooldown

### ISSUE THREAD

**Issue by VaiskiKP** [UchuServer/Uchu#60]
Specific smashable doesn't have a respawn cooldown. I also think I've seen this same thing happen to one of the crates at Sentinel Point Zeta at CP
[Video](https://youtu.be/m3jDAhI0g8gl)

**Comment by TheNexusAvenger** [comment]
This bug is actually a general case where if a smashable reveals a quickbuild, the quickbuild is always visible and the smashable instantly respawns instead of waiting for the smashable or built component to be destroyed. Cases where this happens include:
- The mech rebuild near Wisp Lee in Avant Gardens.
- The pirate gate in Gnarled Forest.
- Bouncers in Nexus Tower and Crux Prime.
- Platforms in Crux Prime.
